# config/config.yaml
model_path: resources/trained_models/60000_drafts_models
partial_sequence_path: resources/partial_sequence.txt
tokenizer_path: resources/tokenizer
champions_path: resources/data/champions.csv
draft_tokens_path: resources/data/draft_tokens
train_dataset_path: resources/datasets/train.csv
val_dataset_path: resources/datasets/val.csv
test_dataset_path: resources/datasets/test.csv
eval_output_path: outputs/eval_results/results.txt
max_length: 42
batch_size: 64
num_epochs: 2000