# config/config.yaml
model_path: resources/trained_models/model_from_25_16/checkpoint-484
partial_sequence_path: resources/partial_sequence.txt
tokenizer_path: resources/tokenizer
champions_path: resources/data/champions.csv
draft_tokens_path: resources/data/draft_tokens
train_dataset_path: resources/datasets/train_from_25_16.csv
val_dataset_path: resources/datasets/val_from_25_16.csv
test_dataset_path: resources/datasets/test_from_25_16.csv
max_length: 42
batch_size: 64
num_epochs: 50