# config/train_config.yaml
model_path: resources/trained_models/drafts_context_tokens_model
partial_sequence_path: resources/custom_sequences/partial_sequence.txt
tokenizer_path: resources/tokenizer
champions_path: resources/vocab/champions.txt
draft_tokens_path: resources/data/draft_tokens.txt
train_dataset_path: resources/datasets/train_from_25_16.csv
val_dataset_path: resources/datasets/val_from_25_16.csv
test_dataset_path: resources/datasets/test_from_25_16.csv
max_length: 50
batch_size: 64
num_epochs: 50